# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_world.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hello_world.proto\x12\x16gromlin2.howtogenerate\"C\n\x0bHelloPlanet\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06planet\x18\x02 \x01(\t\x12\x13\n\x0b\x62\x65_friendly\x18\x03 \x01(\x08\"G\n\rDebtsAtPlanet\x12\x1e\n\x16\x61mount_of_cash_carried\x18\x01 \x01(\r\x12\x16\n\x0e\x61mount_of_debt\x18\x02 \x01(\x05\"3\n\tSpaceShip\x12\x11\n\tmax_speed\x18\x01 \x01(\x04\x12\x13\n\x0bwarp_energy\x18\x02 \x01(\x03\"\x99\x01\n\tByePlanet\x12\x43\n\x08reaction\x18\x01 \x01(\x0e\x32\x31.gromlin2.howtogenerate.ByePlanet.GoodByeReaction\"G\n\x0fGoodByeReaction\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x13\n\x0fNEVER_COME_BACK\x10\x01\x12\x12\n\x0e\x41LWAYS_WELCOME\x10\x02\x32r\n\x1aInterplantaryCommunication\x12T\n\x08\x43\x61llHome\x12#.gromlin2.howtogenerate.HelloPlanet\x1a!.gromlin2.howtogenerate.ByePlanet\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_world_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOPLANET._serialized_start=45
  _HELLOPLANET._serialized_end=112
  _DEBTSATPLANET._serialized_start=114
  _DEBTSATPLANET._serialized_end=185
  _SPACESHIP._serialized_start=187
  _SPACESHIP._serialized_end=238
  _BYEPLANET._serialized_start=241
  _BYEPLANET._serialized_end=394
  _BYEPLANET_GOODBYEREACTION._serialized_start=323
  _BYEPLANET_GOODBYEREACTION._serialized_end=394
  _INTERPLANTARYCOMMUNICATION._serialized_start=396
  _INTERPLANTARYCOMMUNICATION._serialized_end=510
# @@protoc_insertion_point(module_scope)
