name: Build and Test

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  helloWorld:
    name: Build and test hello world
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Install hello-world dependencies
        working-directory: hello_world_generator
        run: pip install -r requirements.txt

      - name: Check formatting
        working-directory: hello_world_generator
        run: black --check ./

      - name: Test hello-world
        working-directory: hello_world_generator/test
        run: pytest --verbose

  protoSummaries:
    name: Build and test summary generator
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Install summarizer dependencies
        working-directory: proto_summarizer
        run: pip install -r requirements.txt

      - name: Check formatting
        working-directory: hello_world_generator
        run: black --check ./

      - name: Test summarizer
        working-directory: proto_summarizer
        run: pytest --verbose
